apiVersion: v1
kind: Service
metadata:
  name: swstravel04-service-y
spec:
  selector:
    app: swstravel04-microservice-y
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
